[versions]
androidx-webkit = "1.12.1"
androidx-core = "1.15.0"
junit = "4.13.2"

[libraries]
androidx-webkit = { module = "androidx.webkit:webkit", version.ref = "androidx-webkit" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
junit = { module = "junit:junit", version.ref = "junit" }
